[project]
name = "autist-soundboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydub>=0.25.1",
    "uvicorn>=0.22.0",
]
